version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    assignees:
      - "bobokun"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    assignees:
      - "bobokun"
    ignore:
      - dependency-name: "salsify/action-detect-and-tag-new-version"
